[theme]
primaryColor = "#0284c7"
backgroundColor = "#0b1329"
secondaryBackgroundColor = "#111f43"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
